name: dating_app_prototype
description: A basic Flutter dating app prototype (source only). Build with Flutter SDK & configure Firebase.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  provider: ^6.0.5
  swipe_cards: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
